# Generated by Django 6.1.1 on 2026-09-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], max_length=20)),
                ('experience_min', models.PositiveIntegerField(default=0)),
                ('experience_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'), models.Index(fields=['experience_min'], name='jobs_job_experie_a96fde_idx'), models.Index(fields=['salary_min'], name='jobs_job_salary__a70ca3_idx'), models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx')],
            },
        ),
    ]
