# Generated by Django 6.1.1 on 2026-09-16 15:36

import secure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=secure_storage.SecureResumeStorage(), upload_to='resumes/'),
        ),
    ]
